import type { MobileApp, MobileAppCategory } from "./apps";

// Extended AppLeap catalog: additional popular apps beyond the core set
// (phone, messages, mail, gmail, claude, gemini, google, uber, grab,
// google-maps, whatsapp, telegram, instagram, x, spotify, youtube,
// myfitnesspal), which already live in ./apps.
//
// Data below is best-effort seed data, same spirit as the original catalog:
// schemes/packages/store ids were researched against public sources
// (iTunes Search API, official app listings, well-documented deep-link
// guides) but a wrong iosScheme/androidScheme/androidPackage just
// degrades to the App Store / Play Store fallback, so mistakes fail soft.
// Where a custom scheme could not be confirmed with reasonable
// confidence, it was omitted in favor of the https:// universalLink,
// per the "wrong universal link still opens a normal web page" guidance.

export const EXTENDED_CATEGORIES: MobileAppCategory[] = [
  { id: "productivity", name: "Productivity" },
  { id: "travel", name: "Travel" },
  { id: "finance", name: "Finance" },
  { id: "shopping", name: "Shopping" },
  { id: "food", name: "Food" },
];

export const EXTENDED_APPS: MobileApp[] = [
  // --- Social ---
  {
    slug: "facebook",
    name: "Facebook",
    categoryId: "social",
    icon: "📘",
    accent: "from-blue-600 to-indigo-700",
    tagline: "Catch up with friends and Groups",
    universalLink: "https://www.facebook.com",
    iosScheme: "fb://",
    androidScheme: "fb",
    androidPackage: "com.facebook.katana",
    appStoreUrl: "https://apps.apple.com/app/id284882215",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.facebook.katana",
  },
  {
    slug: "messenger",
    name: "Messenger",
    categoryId: "social",
    icon: "💬",
    accent: "from-blue-500 to-fuchsia-500",
    tagline: "Free chats and calls with friends",
    universalLink: "https://www.messenger.com",
    iosScheme: "fb-messenger://",
    androidScheme: "fb-messenger",
    androidPackage: "com.facebook.orca",
    appStoreUrl: "https://apps.apple.com/app/id454638411",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.facebook.orca",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    categoryId: "social",
    icon: "🎵",
    accent: "from-cyan-400 to-fuchsia-600",
    tagline: "Short videos that never stop scrolling",
    universalLink: "https://www.tiktok.com",
    iosScheme: "tiktok://",
    androidScheme: "tiktok",
    androidPackage: "com.zhiliaoapp.musically",
    appStoreUrl: "https://apps.apple.com/app/id835599320",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically",
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    categoryId: "social",
    icon: "👻",
    accent: "from-yellow-300 to-yellow-500",
    tagline: "Snap a photo, share the moment",
    universalLink: "https://www.snapchat.com",
    iosScheme: "snapchat://",
    androidScheme: "snapchat",
    androidPackage: "com.snapchat.android",
    appStoreUrl: "https://apps.apple.com/app/id447188370",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.snapchat.android",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    categoryId: "social",
    icon: "💼",
    accent: "from-sky-600 to-blue-800",
    tagline: "Your professional network, in your pocket",
    universalLink: "https://www.linkedin.com",
    iosScheme: "linkedin://",
    androidScheme: "linkedin",
    androidPackage: "com.linkedin.android",
    appStoreUrl: "https://apps.apple.com/app/id288429040",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.linkedin.android",
  },
  {
    slug: "pinterest",
    name: "Pinterest",
    categoryId: "social",
    icon: "📌",
    accent: "from-red-600 to-rose-700",
    tagline: "Ideas and inspiration worth pinning",
    universalLink: "https://www.pinterest.com",
    iosScheme: "pinterest://",
    androidScheme: "pinterest",
    androidPackage: "com.pinterest",
    appStoreUrl: "https://apps.apple.com/app/id429047995",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.pinterest",
  },
  {
    slug: "reddit",
    name: "Reddit",
    categoryId: "social",
    icon: "👽",
    accent: "from-orange-500 to-orange-700",
    tagline: "The front page of the internet",
    universalLink: "https://www.reddit.com",
    iosScheme: "reddit://",
    androidScheme: "reddit",
    androidPackage: "com.reddit.frontpage",
    appStoreUrl: "https://apps.apple.com/app/id1064216828",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.reddit.frontpage",
  },
  {
    slug: "discord",
    name: "Discord",
    categoryId: "social",
    icon: "🎮",
    accent: "from-indigo-500 to-indigo-700",
    tagline: "Chat, voice and communities in one place",
    universalLink: "https://discord.com",
    iosScheme: "discord://",
    androidScheme: "discord",
    androidPackage: "com.discord",
    appStoreUrl: "https://apps.apple.com/app/id985746746",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.discord",
  },
  {
    slug: "signal",
    name: "Signal",
    categoryId: "social",
    icon: "🔒",
    accent: "from-indigo-400 to-blue-600",
    tagline: "Private messaging, end to end",
    universalLink: "https://signal.org",
    iosScheme: "sgnl://",
    androidScheme: "sgnl",
    androidPackage: "org.thoughtcrime.securesms",
    appStoreUrl: "https://apps.apple.com/app/id874139669",
    playStoreUrl: "https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms",
  },
  {
    slug: "line",
    name: "LINE",
    categoryId: "social",
    icon: "🟢",
    accent: "from-green-400 to-green-600",
    tagline: "Calls, chats and stickers",
    universalLink: "https://line.me",
    iosScheme: "line://",
    androidScheme: "line",
    androidPackage: "jp.naver.line.android",
    appStoreUrl: "https://apps.apple.com/app/id443904275",
    playStoreUrl: "https://play.google.com/store/apps/details?id=jp.naver.line.android",
  },
  {
    slug: "viber",
    name: "Viber",
    categoryId: "social",
    icon: "📞",
    accent: "from-purple-500 to-violet-700",
    tagline: "Free calls and messages worldwide",
    universalLink: "https://www.viber.com",
    iosScheme: "viber://",
    androidScheme: "viber",
    androidPackage: "com.viber.voip",
    appStoreUrl: "https://apps.apple.com/app/id382617920",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.viber.voip",
  },
  {
    slug: "wechat",
    name: "WeChat",
    categoryId: "social",
    icon: "💚",
    accent: "from-green-500 to-emerald-600",
    tagline: "Chat, pay and connect",
    universalLink: "https://www.wechat.com",
    iosScheme: "weixin://",
    androidScheme: "weixin",
    androidPackage: "com.tencent.mm",
    appStoreUrl: "https://apps.apple.com/app/id414478124",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.tencent.mm",
  },
  {
    slug: "threads",
    name: "Threads",
    categoryId: "social",
    icon: "🧵",
    accent: "from-gray-700 to-black",
    tagline: "Join the conversation, text-first",
    universalLink: "https://www.threads.net",
    androidPackage: "com.instagram.barcelona",
    appStoreUrl: "https://apps.apple.com/app/id6446901002",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.instagram.barcelona",
  },

  // --- Media ---
  {
    slug: "netflix",
    name: "Netflix",
    categoryId: "media",
    icon: "🎬",
    accent: "from-red-600 to-red-800",
    tagline: "Movies and shows on demand",
    universalLink: "https://www.netflix.com",
    iosScheme: "nflx://",
    androidScheme: "nflx",
    androidPackage: "com.netflix.mediaclient",
    appStoreUrl: "https://apps.apple.com/app/id363590051",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.netflix.mediaclient",
  },
  {
    slug: "twitch",
    name: "Twitch",
    categoryId: "media",
    icon: "🕹️",
    accent: "from-purple-600 to-purple-800",
    tagline: "Livestreams for gamers and creators",
    universalLink: "https://www.twitch.tv",
    iosScheme: "twitch://",
    androidScheme: "twitch",
    androidPackage: "tv.twitch.android.app",
    appStoreUrl: "https://apps.apple.com/app/id460177396",
    playStoreUrl: "https://play.google.com/store/apps/details?id=tv.twitch.android.app",
  },

  // --- Productivity ---
  {
    slug: "zoom",
    name: "Zoom",
    categoryId: "productivity",
    icon: "🎥",
    accent: "from-blue-500 to-blue-700",
    tagline: "Video calls and meetings",
    universalLink: "https://zoom.us",
    iosScheme: "zoomus://",
    androidScheme: "zoomus",
    androidPackage: "us.zoom.videomeetings",
    appStoreUrl: "https://apps.apple.com/app/id546505307",
    playStoreUrl: "https://play.google.com/store/apps/details?id=us.zoom.videomeetings",
  },
  {
    slug: "slack",
    name: "Slack",
    categoryId: "productivity",
    icon: "#️⃣",
    accent: "from-fuchsia-500 to-purple-600",
    tagline: "Team chat that gets work done",
    universalLink: "https://slack.com",
    iosScheme: "slack://",
    androidScheme: "slack",
    androidPackage: "com.Slack",
    appStoreUrl: "https://apps.apple.com/app/id618783545",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.Slack",
  },
  {
    slug: "notion",
    name: "Notion",
    categoryId: "productivity",
    icon: "📝",
    accent: "from-gray-700 to-black",
    tagline: "Notes, docs and tasks in one app",
    universalLink: "https://www.notion.so",
    iosScheme: "notion://",
    androidScheme: "notion",
    androidPackage: "notion.id",
    appStoreUrl: "https://apps.apple.com/app/id1232780281",
    playStoreUrl: "https://play.google.com/store/apps/details?id=notion.id",
  },
  {
    slug: "figma",
    name: "Figma",
    categoryId: "productivity",
    icon: "🖌️",
    accent: "from-purple-500 to-orange-400",
    tagline: "Design and prototype together",
    universalLink: "https://www.figma.com",
    iosScheme: "figma://",
    appStoreUrl: "https://apps.apple.com/app/id1152747299",
  },
  {
    slug: "github",
    name: "GitHub",
    categoryId: "productivity",
    icon: "🐙",
    accent: "from-gray-700 to-gray-900",
    tagline: "Code, issues and pull requests on the go",
    universalLink: "https://github.com",
    androidPackage: "com.github.android",
    appStoreUrl: "https://apps.apple.com/app/id1477376905",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.github.android",
  },
  {
    slug: "canva",
    name: "Canva",
    categoryId: "productivity",
    icon: "🎨",
    accent: "from-cyan-400 to-purple-600",
    tagline: "Design anything, drag and drop",
    universalLink: "https://www.canva.com",
    iosScheme: "canva://",
    androidScheme: "canva",
    androidPackage: "com.canva.editor",
    appStoreUrl: "https://apps.apple.com/app/id897446215",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.canva.editor",
  },
  {
    slug: "duolingo",
    name: "Duolingo",
    categoryId: "productivity",
    icon: "🦉",
    accent: "from-green-400 to-lime-500",
    tagline: "Learn a language in minutes a day",
    universalLink: "https://www.duolingo.com",
    iosScheme: "duolingo://",
    androidScheme: "duolingo",
    androidPackage: "com.duolingo",
    appStoreUrl: "https://apps.apple.com/app/id570060128",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.duolingo",
  },
  {
    slug: "microsoft-teams",
    name: "Microsoft Teams",
    categoryId: "productivity",
    icon: "👥",
    accent: "from-indigo-500 to-purple-600",
    tagline: "Chat, meet and collaborate at work",
    universalLink: "https://teams.microsoft.com",
    iosScheme: "msteams://",
    androidScheme: "msteams",
    androidPackage: "com.microsoft.teams",
    appStoreUrl: "https://apps.apple.com/app/id1113153706",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.microsoft.teams",
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    categoryId: "productivity",
    icon: "📁",
    accent: "from-green-400 to-blue-500",
    tagline: "Your files, synced everywhere",
    universalLink: "https://drive.google.com",
    iosScheme: "googledrive://",
    androidScheme: "googledrive",
    androidPackage: "com.google.android.apps.docs",
    appStoreUrl: "https://apps.apple.com/app/id507874739",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.google.android.apps.docs",
  },

  // --- Travel ---
  {
    slug: "waze",
    name: "Waze",
    categoryId: "travel",
    icon: "🧭",
    accent: "from-sky-400 to-blue-600",
    tagline: "Community-powered turn-by-turn traffic",
    universalLink: "https://www.waze.com",
    iosScheme: "waze://",
    androidScheme: "waze",
    androidPackage: "com.waze",
    appStoreUrl: "https://apps.apple.com/app/id323229106",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.waze",
  },
  {
    slug: "airbnb",
    name: "Airbnb",
    categoryId: "travel",
    icon: "🏠",
    accent: "from-rose-500 to-pink-600",
    tagline: "Book unique stays and experiences",
    universalLink: "https://www.airbnb.com",
    iosScheme: "airbnb://",
    androidScheme: "airbnb",
    androidPackage: "com.airbnb.android",
    appStoreUrl: "https://apps.apple.com/app/id401626263",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.airbnb.android",
  },
  {
    slug: "booking",
    name: "Booking.com",
    categoryId: "travel",
    icon: "🏨",
    accent: "from-blue-700 to-indigo-800",
    tagline: "Hotels, flights and rentals worldwide",
    universalLink: "https://www.booking.com",
    iosScheme: "booking://",
    androidScheme: "booking",
    androidPackage: "com.booking",
    appStoreUrl: "https://apps.apple.com/app/id367003839",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.booking",
  },

  // --- Finance ---
  {
    slug: "paypal",
    name: "PayPal",
    categoryId: "finance",
    icon: "💳",
    accent: "from-blue-600 to-sky-500",
    tagline: "Send, spend and get paid",
    universalLink: "https://www.paypal.com",
    iosScheme: "paypal://",
    androidScheme: "paypal",
    androidPackage: "com.paypal.android.p2pmobile",
    appStoreUrl: "https://apps.apple.com/app/id283646709",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile",
  },
  {
    slug: "venmo",
    name: "Venmo",
    categoryId: "finance",
    icon: "💸",
    accent: "from-sky-400 to-blue-500",
    tagline: "Split bills and pay friends fast",
    universalLink: "https://venmo.com",
    iosScheme: "venmo://",
    androidScheme: "venmo",
    androidPackage: "com.venmo",
    appStoreUrl: "https://apps.apple.com/app/id351727428",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.venmo",
  },
  {
    slug: "cash-app",
    name: "Cash App",
    categoryId: "finance",
    icon: "💵",
    accent: "from-green-500 to-emerald-600",
    tagline: "Send money and invest instantly",
    universalLink: "https://cash.app",
    iosScheme: "cashme://",
    androidScheme: "cashme",
    androidPackage: "com.squareup.cash",
    appStoreUrl: "https://apps.apple.com/app/id711923939",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.squareup.cash",
  },
  {
    slug: "gcash",
    name: "GCash",
    categoryId: "finance",
    icon: "💰",
    accent: "from-sky-500 to-blue-700",
    tagline: "Pay, send and save, GCash style",
    universalLink: "https://www.gcash.com",
    iosScheme: "gcash://",
    androidScheme: "gcash",
    androidPackage: "com.globe.gcash.android",
    appStoreUrl: "https://apps.apple.com/app/id520020791",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.globe.gcash.android",
  },
  {
    slug: "maya",
    name: "Maya",
    categoryId: "finance",
    icon: "🏦",
    accent: "from-emerald-500 to-teal-600",
    tagline: "Digital bank and e-wallet, PH style",
    universalLink: "https://www.maya.ph",
    androidPackage: "com.paymaya",
    appStoreUrl: "https://apps.apple.com/app/id991673877",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.paymaya",
  },
  {
    slug: "touch-n-go-ewallet",
    name: "Touch 'n Go eWallet",
    categoryId: "finance",
    icon: "🎫",
    accent: "from-blue-600 to-cyan-500",
    tagline: "Malaysia's tap-to-pay wallet",
    universalLink: "https://www.touchngo.com.my",
    androidPackage: "my.com.tngdigital.ewallet",
    appStoreUrl: "https://apps.apple.com/app/id1344696702",
    playStoreUrl: "https://play.google.com/store/apps/details?id=my.com.tngdigital.ewallet",
  },

  // --- Shopping ---
  {
    slug: "amazon",
    name: "Amazon",
    categoryId: "shopping",
    icon: "📦",
    accent: "from-yellow-500 to-orange-600",
    tagline: "Shop millions of products",
    universalLink: "https://www.amazon.com",
    iosScheme: "amazon://",
    androidScheme: "amazon",
    androidPackage: "com.amazon.mShop.android.shopping",
    appStoreUrl: "https://apps.apple.com/app/id297606951",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping",
  },
  {
    slug: "shopee",
    name: "Shopee",
    categoryId: "shopping",
    icon: "🛍️",
    accent: "from-orange-500 to-red-600",
    tagline: "Online shopping, gamified",
    universalLink: "https://shopee.ph",
    androidPackage: "com.shopee.ph",
    appStoreUrl: "https://apps.apple.com/app/id959841854",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.shopee.ph",
  },
  {
    slug: "lazada",
    name: "Lazada",
    categoryId: "shopping",
    icon: "🛒",
    accent: "from-blue-700 to-orange-500",
    tagline: "Southeast Asia's online mall",
    universalLink: "https://www.lazada.com.ph",
    iosScheme: "lazada://",
    androidScheme: "lazada",
    androidPackage: "com.lazada.android",
    appStoreUrl: "https://apps.apple.com/app/id785385147",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.lazada.android",
  },
  {
    slug: "ebay",
    name: "eBay",
    categoryId: "shopping",
    icon: "🏷️",
    accent: "from-red-500 to-blue-600",
    tagline: "Buy and sell just about anything",
    universalLink: "https://www.ebay.com",
    iosScheme: "ebay://",
    androidScheme: "ebay",
    androidPackage: "com.ebay.mobile",
    appStoreUrl: "https://apps.apple.com/app/id282614216",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ebay.mobile",
  },

  // --- Food ---
  {
    slug: "foodpanda",
    name: "foodpanda",
    categoryId: "food",
    icon: "🐼",
    accent: "from-pink-500 to-rose-600",
    tagline: "Food and grocery delivery",
    universalLink: "https://www.foodpanda.ph",
    iosScheme: "foodpanda://",
    androidScheme: "foodpanda",
    androidPackage: "com.global.foodpanda.android",
    appStoreUrl: "https://apps.apple.com/app/id758103884",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.global.foodpanda.android",
  },
];
